/* tslint:disable */
/* eslint-disable */
/**
 * Благотворительное приложение API
 * API для благотворительного приложения \"Помощь\"
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api.ts";
export * from "./configuration.ts";

